name: Build Windows EXE

on:
  push:
    branches: [ "main" ]  # 仅当 main 分支有推送时触发
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    runs-on: windows-latest  # 使用 GitHub 的 Windows 虚拟机

    steps:
    - name: 拉取代码
      uses: actions/checkout@v4  # 将代码克隆到虚拟机

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"  # 指定 Python 版本

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 打包 EXE
      run: |
        pyinstaller --onefile --noconsole --name "Excel合并工具" merge_excel.py

    - name: 上传成品
      uses: actions/upload-artifact@v3
      with:
        name: Excel合并工具  # 产物名称
        path: dist/Excel合并工具.exe  # 打包生成的 EXE 路径
